[package]
name = "corpus_generator"
version = "0.1.0"
authors = ["Outurnate <joseph@outurnate.com>"]
edition = "2018"

[[bin]]
name = "corpus_generator"
path = "src/corpus.rs"

[dependencies]
regex = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }